node('currikistage') {
    stage('Clone repository') {               
        checkout scm    
    }  
    stage ('Copy H5P to currikistage') {
            echo 'Copy'
            sh "yes | rm -rf /tmp/h5p-dist3" 
            sh "yes | git clone https://github.com/ActiveLearningStudio/H5P.Distribution.git /tmp/h5p-dist3" 
            sh "yes | cp -rf /tmp/h5p-dist3/* /root/curriki/api/storage/app/public/h5p/libraries/"
            echo 'Copy completed'
    }
}
